/**
 * Every URL in the Keyword Map & Sitemap v2 (Sika Digital, 2 Oct 2026) — the single
 * source of truth for routing, metadata keywords and the XML sitemap.
 * Generated from the "Sitemap" sheet. Tier 1 = launch · 2 = this project · 3 = post-launch.
 * Flip `built` to true as each page ships; only built, indexable routes enter sitemap.xml.
 */
export type Route = {
  path: string;
  section: string;
  template: string;
  keyword: string | null;
  volume: number | null;
  kd: number | null;
  tier: 1 | 2 | 3;
  noindex: boolean;
  built: boolean;
};

export const routes: Route[] = [
  {
    path: "/",
    section: "Core",
    template: "Home",
    keyword: "renovation builders melbourne",
    volume: 720,
    kd: 22,
    tier: 1,
    noindex: false,
    built: true
  },
  {
    path: "/about/",
    section: "Core",
    template: "About",
    keyword: "forefront trades co",
    volume: 90,
    kd: 25,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/design-and-construct/",
    section: "Core",
    template: "Differentiator",
    keyword: "design and construct",
    volume: 480,
    kd: 12,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/projects/",
    section: "Proof",
    template: "Projects hub",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/projects/footscray/",
    section: "Proof",
    template: "Case study",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/projects/altona/",
    section: "Proof",
    template: "Case study (existing URL)",
    keyword: "bathroom renovation altona",
    volume: 90,
    kd: 6,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/projects/bentleigh/",
    section: "Proof",
    template: "Case study",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/projects/west-footscray/",
    section: "Proof",
    template: "Case study",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/projects/brookfield/",
    section: "Proof",
    template: "Case study",
    keyword: null,
    volume: null,
    kd: null,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/projects/craigieburn/",
    section: "Proof",
    template: "Case study",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/projects/clifton-hill/",
    section: "Proof",
    template: "Case study",
    keyword: "home builders clifton hill",
    volume: 90,
    kd: 6,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/reviews/",
    section: "Proof",
    template: "Reviews hub",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/warranty-and-insurance/",
    section: "Trust",
    template: "Trust",
    keyword: "domestic building insurance victoria",
    volume: 140,
    kd: 18,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/faqs/",
    section: "Trust",
    template: "FAQ hub",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/contact/",
    section: "Core",
    template: "Contact / GBP",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/book-a-consultation/",
    section: "Conversion",
    template: "Enquiry",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-extensions/",
    section: "Extensions",
    template: "Service pillar",
    keyword: "home extensions melbourne",
    volume: 1000,
    kd: 24,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-extensions/second-storey/",
    section: "Extensions",
    template: "Service",
    keyword: "second storey extension",
    volume: 720,
    kd: 17,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-extensions/ground-floor/",
    section: "Extensions",
    template: "Service",
    keyword: "ground floor extension",
    volume: 210,
    kd: 13,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/",
    section: "Renovations",
    template: "Service pillar",
    keyword: "home renovations melbourne",
    volume: 1600,
    kd: 36,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/",
    section: "Renovations",
    template: "Service pillar (existing URL)",
    keyword: "bathroom renovations melbourne",
    volume: 3600,
    kd: 44,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/ensuites/",
    section: "Renovations",
    template: "Service",
    keyword: "ensuite renovation",
    volume: 480,
    kd: 10,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/",
    section: "Renovations",
    template: "Service pillar",
    keyword: "kitchen renovations melbourne",
    volume: 2400,
    kd: 54,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/laundry-renovations/",
    section: "Renovations",
    template: "Service",
    keyword: "laundry renovations melbourne",
    volume: 1000,
    kd: 7,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/heritage-renovations/",
    section: "Renovations",
    template: "Service",
    keyword: "period home renovations",
    volume: 110,
    kd: 18,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/knock-down-rebuild/",
    section: "Confirm",
    template: "Service (if offered)",
    keyword: "knock down rebuild melbourne",
    volume: 1300,
    kd: 16,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/granny-flats/",
    section: "Confirm",
    template: "Service (if offered)",
    keyword: "granny flat builders melbourne",
    volume: 320,
    kd: 30,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/renovation-cost-calculator/",
    section: "Tool",
    template: "Calculator",
    keyword: "renovation cost calculator",
    volume: 480,
    kd: 17,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/areas/",
    section: "Locations",
    template: "Areas we service (by council)",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/guides/",
    section: "Content",
    template: "Guides hub",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/privacy-policy/",
    section: "Legal",
    template: "Legal",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/terms/",
    section: "Legal",
    template: "Legal",
    keyword: null,
    volume: null,
    kd: null,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/brunswick/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations brunswick",
    volume: 140,
    kd: 6,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/yarraville/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations yarraville",
    volume: 70,
    kd: 6,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/essendon/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations essendon",
    volume: 70,
    kd: 7,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/newport/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations newport",
    volume: 70,
    kd: 5,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/maribyrnong/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations maribyrnong",
    volume: 50,
    kd: 0,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/moonee-ponds/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations moonee ponds",
    volume: 50,
    kd: 5,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/ascot-vale/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations ascot vale",
    volume: 50,
    kd: 0,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/footscray/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations footscray",
    volume: 30,
    kd: 0,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-extensions/yarraville/",
    section: "Suburbs",
    template: "Suburb – extensions",
    keyword: "home extensions yarraville",
    volume: 70,
    kd: 6,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-extensions/ascot-vale/",
    section: "Suburbs",
    template: "Suburb – extensions",
    keyword: "home extensions ascot vale",
    volume: 70,
    kd: 7,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-extensions/brunswick/",
    section: "Suburbs",
    template: "Suburb – extensions",
    keyword: "home extensions brunswick",
    volume: 70,
    kd: 7,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-extensions/maribyrnong/",
    section: "Suburbs",
    template: "Suburb – extensions",
    keyword: "home extensions maribyrnong",
    volume: 40,
    kd: 0,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/essendon/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations essendon",
    volume: 880,
    kd: 7,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/yarraville/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations yarraville",
    volume: 720,
    kd: 6,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/moonee-ponds/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations moonee ponds",
    volume: 590,
    kd: 6,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/footscray/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations footscray",
    volume: 480,
    kd: 8,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/brunswick/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations brunswick",
    volume: 480,
    kd: 7,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/newport/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations newport",
    volume: 480,
    kd: 7,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/spotswood/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations spotswood",
    volume: 390,
    kd: 8,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/maribyrnong/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations maribyrnong",
    volume: 170,
    kd: 9,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/footscray/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations footscray",
    volume: 390,
    kd: 6,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/brunswick/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations brunswick",
    volume: 390,
    kd: 6,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/maribyrnong/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations maribyrnong",
    volume: 110,
    kd: 7,
    tier: 1,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/pascoe-vale/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations pascoe vale",
    volume: 50,
    kd: 4,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/albion/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations albion",
    volume: 40,
    kd: 0,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/seddon/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations seddon",
    volume: 10,
    kd: 0,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/sunshine/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations sunshine",
    volume: 10,
    kd: 0,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/spotswood/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations spotswood",
    volume: 10,
    kd: 0,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/flemington/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations flemington",
    volume: 0,
    kd: 0,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/kensington/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations kensington",
    volume: 0,
    kd: 0,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/home-extensions/albion/",
    section: "Suburbs",
    template: "Suburb – extensions",
    keyword: "home extensions albion",
    volume: 40,
    kd: 0,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/ascot-vale/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations ascot vale",
    volume: 320,
    kd: 6,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/seddon/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations seddon",
    volume: 260,
    kd: 6,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/kensington/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations kensington",
    volume: 260,
    kd: 6,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/flemington/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations flemington",
    volume: 210,
    kd: 6,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/pascoe-vale/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations pascoe vale",
    volume: 210,
    kd: 5,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/sunshine/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations sunshine",
    volume: 140,
    kd: 5,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/essendon/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations essendon",
    volume: 320,
    kd: 9,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/ascot-vale/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations ascot vale",
    volume: 320,
    kd: 7,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/yarraville/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations yarraville",
    volume: 260,
    kd: 8,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/flemington/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations flemington",
    volume: 210,
    kd: 6,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/kensington/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations kensington",
    volume: 170,
    kd: 14,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/moonee-ponds/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations moonee ponds",
    volume: 140,
    kd: 8,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/laundry-renovations/essendon/",
    section: "Suburbs",
    template: "Suburb – laundry",
    keyword: "laundry renovations essendon",
    volume: 70,
    kd: 5,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/laundry-renovations/brunswick/",
    section: "Suburbs",
    template: "Suburb – laundry",
    keyword: "laundry renovations brunswick",
    volume: 50,
    kd: 4,
    tier: 2,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/kingsville/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations kingsville",
    volume: 20,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/melbourne-cbd/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations melbourne cbd",
    volume: 20,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/maidstone/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations maidstone",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/west-footscray/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations west footscray",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/tottenham/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations tottenham",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/braybrook/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations braybrook",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/sunshine-north/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations sunshine north",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/sunshine-west/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations sunshine west",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/avondale-heights/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations avondale heights",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/essendon-west/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations essendon west",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/aberfeldie/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations aberfeldie",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/essendon-north/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations essendon north",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/travancore/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations travancore",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/niddrie/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations niddrie",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/airport-west/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations airport west",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/keilor-east/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations keilor east",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/strathmore/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations strathmore",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/strathmore-heights/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations strathmore heights",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/pascoe-vale-south/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations pascoe vale south",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/brunswick-west/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations brunswick west",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/north-melbourne/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations north melbourne",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/west-melbourne/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations west melbourne",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/parkville/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations parkville",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/docklands/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations docklands",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/south-kingsville/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations south kingsville",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/brooklyn/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations brooklyn",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/home-renovations/altona-north/",
    section: "Suburbs",
    template: "Suburb hub – renovations & extensions",
    keyword: "home renovations altona north",
    volume: 0,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/albion/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations albion",
    volume: 90,
    kd: 5,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/maidstone/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations maidstone",
    volume: 70,
    kd: 7,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/kingsville/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations kingsville",
    volume: 70,
    kd: 14,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/strathmore/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations strathmore",
    volume: 70,
    kd: 7,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/parkville/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations parkville",
    volume: 70,
    kd: 6,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/brooklyn/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations brooklyn",
    volume: 70,
    kd: 13,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/avondale-heights/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations avondale heights",
    volume: 50,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/keilor-east/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations keilor east",
    volume: 50,
    kd: 6,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/bathroom-renovations/north-melbourne/",
    section: "Suburbs",
    template: "Suburb – bathroom",
    keyword: "bathroom renovations north melbourne",
    volume: 50,
    kd: 4,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/sunshine/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations sunshine",
    volume: 110,
    kd: 13,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/pascoe-vale/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations pascoe vale",
    volume: 110,
    kd: 5,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/newport/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations newport",
    volume: 110,
    kd: 5,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/spotswood/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations spotswood",
    volume: 70,
    kd: 5,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/maidstone/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations maidstone",
    volume: 50,
    kd: 7,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/seddon/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations seddon",
    volume: 50,
    kd: 6,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/avondale-heights/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations avondale heights",
    volume: 50,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/keilor-east/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations keilor east",
    volume: 50,
    kd: 4,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/strathmore/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations strathmore",
    volume: 50,
    kd: 0,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/parkville/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations parkville",
    volume: 50,
    kd: 4,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/kitchen-renovations/brooklyn/",
    section: "Suburbs",
    template: "Suburb – kitchen",
    keyword: "kitchen renovations brooklyn",
    volume: 50,
    kd: 23,
    tier: 3,
    noindex: false,
    built: false
  },
  {
    path: "/lp/home-extensions/",
    section: "Paid",
    template: "Landing page (noindex)",
    keyword: "Paid traffic only",
    volume: null,
    kd: null,
    tier: 1,
    noindex: true,
    built: false
  },
  {
    path: "/lp/bathroom-renovations/",
    section: "Paid",
    template: "Landing page (noindex)",
    keyword: "Paid traffic only",
    volume: null,
    kd: null,
    tier: 1,
    noindex: true,
    built: false
  },
  {
    path: "/lp/kitchen-renovations/",
    section: "Paid",
    template: "Landing page (noindex)",
    keyword: "Paid traffic only",
    volume: null,
    kd: null,
    tier: 1,
    noindex: true,
    built: false
  },
  {
    path: "/lp/laundry-renovations/",
    section: "Paid",
    template: "Landing page (noindex)",
    keyword: "Paid traffic only",
    volume: null,
    kd: null,
    tier: 2,
    noindex: true,
    built: false
  },
  {
    path: "/lp/full-home-renovation/",
    section: "Paid",
    template: "Landing page (noindex)",
    keyword: "Paid traffic only",
    volume: null,
    kd: null,
    tier: 2,
    noindex: true,
    built: false
  }
];
